"""
JS/Python parity tests — verify Python output matches JS reference fixture.

The fixture was generated by running the JS engine via Node.js.
"""

import json
import os

import numpy as np
import pytest

from data.prng import Mulberry32
from data.synthetic import generate_prices, generate_dataset
from backtest.synthetic_demo import run_synthetic_backtest, BacktestConfig
from factors.scoring import compute_factor_scores_js
from factors.registry import JS_FACTOR_NAMES

FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "js_reference_output.json")


@pytest.fixture(scope="module")
def js_ref():
    with open(FIXTURE_PATH) as f:
        return json.load(f)


class TestPRNGParity:
    def test_seed_42_10000_samples(self, js_ref):
        """All 10,000 PRNG values from seed=42 match JS exactly."""
        expected = js_ref["prng"]["42"]
        rng = Mulberry32(42)
        for i in range(len(expected)):
            actual = rng()
            assert actual == pytest.approx(expected[i], abs=1e-15), (
                f"Mismatch at sample {i}: expected {expected[i]}, got {actual}"
            )

    def test_seed_0(self, js_ref):
        expected = js_ref["prng"]["0"]
        rng = Mulberry32(0)
        for i in range(len(expected)):
            assert rng() == pytest.approx(expected[i], abs=1e-15)

    def test_seed_99(self, js_ref):
        expected = js_ref["prng"]["99"]
        rng = Mulberry32(99)
        for i in range(len(expected)):
            assert rng() == pytest.approx(expected[i], abs=1e-15)

    def test_seed_12345(self, js_ref):
        expected = js_ref["prng"]["12345"]
        rng = Mulberry32(12345)
        for i in range(len(expected)):
            assert rng() == pytest.approx(expected[i], abs=1e-15)


class TestPriceParity:
    def test_aapl_prices(self, js_ref):
        """AAPL price at key indices matches JS."""
        ref = js_ref["prices"]["AAPL"]
        prices, _ = generate_prices("AAPL", 504, 42)
        assert len(prices) == ref["length"]
        assert prices[0] == pytest.approx(ref["close_0"], rel=1e-10)
        assert prices[252] == pytest.approx(ref["close_252"], rel=1e-10)
        assert prices[504] == pytest.approx(ref["close_504"], rel=1e-10)

    def test_msft_prices(self, js_ref):
        ref = js_ref["prices"]["MSFT"]
        prices, _ = generate_prices("MSFT", 504, 42)
        assert len(prices) == ref["length"]
        assert prices[0] == pytest.approx(ref["close_0"], rel=1e-10)
        assert prices[252] == pytest.approx(ref["close_252"], rel=1e-10)
        assert prices[504] == pytest.approx(ref["close_504"], rel=1e-10)

    def test_nvda_prices(self, js_ref):
        ref = js_ref["prices"]["NVDA"]
        prices, _ = generate_prices("NVDA", 504, 42)
        assert len(prices) == ref["length"]
        assert prices[0] == pytest.approx(ref["close_0"], rel=1e-10)
        assert prices[252] == pytest.approx(ref["close_252"], rel=1e-10)
        assert prices[504] == pytest.approx(ref["close_504"], rel=1e-10)


class TestFactorScoreParity:
    def test_tech_factor_scores(self, js_ref):
        """Factor z-scores for Tech sector match JS."""
        dataset = generate_dataset("Technology", 252, 42)
        scores = compute_factor_scores_js(dataset, 252)

        for ticker, ref_scores in js_ref["factor_scores"].items():
            if ticker not in scores:
                continue
            py_scores = scores[ticker]
            for factor in JS_FACTOR_NAMES:
                assert py_scores[factor] == pytest.approx(
                    ref_scores[factor], abs=1e-6
                ), f"{ticker}/{factor}: expected {ref_scores[factor]}, got {py_scores[factor]}"

    def test_composite_and_signal(self, js_ref):
        dataset = generate_dataset("Technology", 252, 42)
        scores = compute_factor_scores_js(dataset, 252)

        for ticker, ref_scores in js_ref["factor_scores"].items():
            if ticker not in scores:
                continue
            assert scores[ticker]["_composite"] == pytest.approx(
                ref_scores["_composite"], abs=1e-4
            )
            assert scores[ticker]["_signal"] == ref_scores["_signal"]


class TestBacktestParity:
    def test_backtest_metrics(self, js_ref):
        """Backtest metrics match JS reference."""
        ref = js_ref["backtest"]
        config = BacktestConfig(sector="Technology", lookback=252)
        result = run_synthetic_backtest(config)

        assert len(result.nav) == ref["nav_length"]
        assert result.nav[0] == pytest.approx(ref["nav_first"], abs=1e-6)
        assert result.nav[-1] == pytest.approx(ref["nav_last"], rel=0.01)
        assert result.metrics.sharpe == pytest.approx(ref["sharpe"], rel=0.05)
        assert result.metrics.total_return == pytest.approx(ref["total_return"], rel=0.05)
        assert result.metrics.max_dd == pytest.approx(ref["max_dd"], rel=0.05)
        assert result.metrics.win_rate == pytest.approx(ref["win_rate"], rel=0.05)
